### ISSUE TITLE
Vanilla Minecraft Feature Tracking

### ISSUE THREAD

**Issue by DaPigGuy** [dragonfly-tech/dragonfly#566]
Tracking implementation of various vanilla Minecraft features into dragonfly. 

**Gameplay**
* [ ] [Cauldrons](https://minecraft.wiki/w/Cauldron)
* [ ] [End Portals](https://minecraft.wiki/w/End_portal)
* [ ] Entity AI
* [ ] Entity Riding API (#1119)
  * [x] Requires entity unique ID saving (#524)
* [ ] [Fishing](https://minecraft.wiki/w/Fishing) (#671)
  * [ ] Requires entity riding (#330)
* [ ] Light updates
* [ ] [Nether Portals ](https://minecraft.wiki/w/Nether_portal)(#426)
* [ ] [Boats](https://minecraft.wiki/w/Boat)
  * [ ] Requires entity riding (#330)
* [ ] [Minecarts](https://minecraft.wiki/w/Minecart)
  * [ ] Requires rails
  * [ ] Requires entity riding (#330)
* [ ] [Redstone](https://minecraft.wiki/w/Redstone_(disambiguation))
* [ ] [World Generation (Vanilla)](https://minecraft.wiki/w/History_of_world_generation#Bedrock_Edition)
* [ ] [Armor Stands](https://minecraft.wiki/w/Armor_Stand) (#723)

**General Blocks**
* [ ] [Lodestones](https://minecraft.wiki/w/Lodestone)
* [ ] [Mushrooms](https://minecraft.wiki/w/Mushroom)
* [ ] [Powdered Snow](https://minecraft.wiki/w/Powder_Snow)
* [ ] [Rails](https://minecraft.wiki/w/Rail)
* [ ] [Scaffolding](https://minecraft.wiki/w/Scaffolding)
* [ ] [Snow Layer](https://minecraft.wiki/w/Snow) (#871)
* [ ] [Ice](https://minecraft.wiki/w/Ice) (#724 Dec 28 2022)
  * Melting is broken
* [ ] [Bells](https://minecraft.wiki/w/Bell) (#645)
* [ ] [Slime Block](https://minecraft.wiki/w/Slime_Block) (#445)

**General Items**
* [ ] [Paintings](https://minecraft.wiki/w/Painting)
* [ ] [Trident](https://minecraft.wiki/w/Trident)
* [ ] [Shields](https://minecraft.wiki/w/Shield) (#888 #643)

**Enchantments**
* [ ] [Smite](https://minecraft.wiki/w/Smite), [Bane of Arthropods](https://minecraft.wiki/w/Bane_of_Arthropods)
  * [ ] Requires mobs
* [ ] [Looting](https://minecraft.wiki/w/Looting)
  * [ ] Requires mobs
* [ ] [Luck of the Sea](https://minecraft.wiki/w/Luck_of_the_Sea), [Lure](https://minecraft.wiki/w/Lure)
  * [ ] Requires fishing
* [ ] [Impaling](https://minecraft.wiki/w/Impaling), [Riptide](https://minecraft.wiki/w/Riptide), [Loyalty](https://minecraft.wiki/w/Loyalty), [Channeling](https://minecraft.wiki/w/Channeling)
  * [ ] Requires tridents
* [ ] [Piercing](https://minecraft.wiki/w/Piercing)
* [ ] [Curse of Binding](https://minecraft.wiki/w/Curse_of_Binding) (#716)
* [ ] [Frost Walker](https://minecraft.wiki/w/Frost_Walker) (#722)

---

**Pending**
* [ ] [Shulker Boxes](https://minecraft.wiki/w/Shulker_Box) (#956)

---
**Implemented in v0.11**
* [x] [Sleeping](https://minecraft.wiki/w/Bed#Sleeping) (#1158)
* [x] [Fortune](https://minecraft.wiki/w/Fortune)
* [x] [Multishot](https://minecraft.wiki/w/Multishot) (#1027)

**Implemented in v0.10**
* [x] [Crossbow](https://minecraft.wiki/w/Crossbow) (#957)
  * [x] [Quick Charge](https://minecraft.wiki/w/Quick_Charge) (#957)
* [x] [Vines](https://minecraft.wiki/w/Vines) (#578 #572)
* [x] [Brewing](https://minecraft.fandom.com/wiki/Brewing) (#520 #632)
* [x] [Campfire](https://minecraft.fandom.com/wiki/Campfire) (#914)
* [x] [Hopper](https://minecraft.fandom.com/wiki/Hopper) (#911)
  * [ ] Locking dependent on redstone, can be merged anyway
* [x] [Double Chests](https://minecraft.fandom.com/wiki/Chest#Usage) (#872)
* [x] [Armour Trims](https://minecraft.fandom.com/wiki/Smithing_Template) (#861)
* [x] [Lecterns](https://minecraft.fandom.com/wiki/Lectern) (#651)
* [x] [Totem of Undying](https://minecraft.fandom.com/wiki/Totem_of_Undying) (#858)

**Implemented in v0.9**
* [x] [Suspicious Stew](https://minecraft.fandom.com/wiki/Suspicious_Stew) (#664 Sep 8 2022)
* [x] [Curse of Vanishing](https://minecraft.fandom.com/wiki/Curse_of_Vanishing) (#661 Aug 29 2022)
* [x] [Book and Quill](https://minecraft.fandom.com/wiki/Book_and_Quill)/[Written Book](https://minecraft.fandom.com/wiki/Written_Book) (#608 Aug 19 2022)
* [x] [Composter](https://minecraft.fandom.com/wiki/Composter) (#624 Aug 19 2022)
* [x] [Recovery Compass](https://minecraft.fandom.com/wiki/Recovery_Compass) (#627 Aug 19 2022)
* [x] [Grindstones](https://minecraft.fandom.com/wiki/Grindstone) (#630  #501 Aug 15 2022)
* [x] [Sugar Cane](https://minecraft.fandom.com/wiki/Sugar_Cane) (#631 Aug 14 2022)

**Implemented in v0.8**
* [x] [Elytra](https://minecraft.fandom.com/wiki/Elytra) (#597 Aug 3 2022)
* [x] [Blackstone](https://minecraft.fandom.com/wiki/Blackstone)/[Deepslate](https://minecraft.fandom.com/wiki/Deepslate) (#611  Aug 1 2022)
* [x] [Fire Charge](https://minecraft.fandom.com/wiki/Fire_Charge) (#621  Aug 1 2022)
* [x] [Milk Bucket](https://minecraft.fandom.com/wiki/Milk_Bucket) (#598 Aug 1 2022)
* [x] [Slabs](https://minecraft.fandom.com/wiki/Slab) (#586 Aug 1 2022)
* [x] [Lingering Potions](https://minecraft.fandom.com/wiki/Lingering_Potion) (#586 Aug 1 2022)
* [x] [Loom](https://minecraft.fandom.com/wiki/Loom) (#600 Aug 1 2022)
* [x] [Banners](https://minecraft.fandom.com/wiki/Banner) (#588 Aug 1 2022)
* [x] [Jukeboxes](https://minecraft.fandom.com/wiki/Jukebox) (#589 Aug 1 2022)
* [x] [Stairs](https://minecraft.fandom.com/wiki/Stair) (#618   Aug 1 2022)
* [x] [Power](https://minecraft.fandom.com/wiki/Power), [Flame](https://minecraft.fandom.com/wiki/Flame), [Punch](https://minecraft.fandom.com/wiki/Punch), [Infinity](https://minecraft.fandom.com/wiki/Infinity) (#550 Jul 31 2022)
* [x] [TNT](https://minecraft.fandom.com/wiki/TNT) (#604 Jul 31 2022)
* [x] [Blast Protection](https://minecraft.fandom.com/wiki/Blast_Protection) (Jul 30 2022)
* [x] [Walls](https://minecraft.fandom.com/wiki/Wall) (#559 Jul 29 2022)
* [x] [XP Bottle](https://minecraft.fandom.com/wiki/Bottle_o%27_Enchanting) (#587 Jul 29 2022)
* [x] [Stonecutter](https://minecraft.fandom.com/wiki/Stonecutter) (#574 #564 Jul 29 2022)
* [x] [Fireworks](https://minecraft.fandom.com/wiki/Firework_Rocket) (#576 Jul 29 2022)
* [x] [Explosions](https://minecraft.fandom.com/wiki/Explosion) (#562 Jul 29 2022)
* [x] [Goat Horns](https://minecraft.fandom.com/wiki/Goat_Horn) (#584 Jul 29 2022)
* [x] [Mob Heads](https://minecraft.fandom.com/wiki/Head) (#396 Jul 17 2022)
* [x] [Smelting](https://minecraft.fandom.com/wiki/Smelting) (#508 #499 Jul 17 2022)
* [x] [Enchanting Tables](https://minecraft.fandom.com/wiki/Enchanting_Table) (#548 #502 Jul 16 2022)
* [x] [Thorns](https://minecraft.fandom.com/wiki/Thorns) (#553 Jul 16 2022)
* [x] [Mending](https://minecraft.fandom.com/wiki/Mending) (#552 Jul 16 2022)
* [x] [Smithing Table](https://minecraft.fandom.com/wiki/Smithing_Table) (#563 Jul 16 2022)
* [x] [Ender Chests](https://minecraft.fandom.com/wiki/Ender_Chest) (#565 #315 Jul 15 2022)
* [x] [Anvils](https://minecraft.fandom.com/wiki/Anvil) (#521 Jul 11 2022)

**Implemented in v0.7**
* [x] [Crafting](https://minecraft.fandom.com/wiki/Crafting) (#331 May 15 2022)
